Algoritmo "Concatenação"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruno C B
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
nome: caractere
numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o nome:")
leia(nome)
escreval("Digite o número:")
leia(numero)

escreval(nome, " : ", numero)

Fimalgoritmo